src/Entity/Percentages.php
<?php

namespace App\Entity;

class Percentages
{

    private $cookies;
    private $privacy;
    private $terms;
    private $forms;

    public function getCookies(): ?int
    {
        return $this->cookies;
    }

    public function setCookies(int $cookies): self
    {
        $this->cookies = $cookies;

        return $this;
    }

    public function getPrivacy(): ?int
    {
        return $this->privacy;
    }

    public function setPrivacy(int $privacy): self
    {
        $this->privacy = $privacy;

        return $this;
    }

    public function getTerms(): ?int
    {
        return $this->terms;
    }

    public function setTerms(int $terms): self
    {
        $this->terms = $terms;

        return $this;
    }

    public function getForms(): ?int
    {
        return $this->forms;
    }

    public function setForms(int $forms): self
    {
        $this->forms = $forms;

        return $this;
    }

    public function getTotal(): ?int
    {
        return (
            $this->cookies +
            $this->privacy +
            $this->terms +
            $this->forms
        ) / 4;
    }

}

templates/web/analysis.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% trans %} Your web {% endtrans %} {% endblock %}

{% block body %}

<h1> {% trans %} Your legal texts {% endtrans %} </h1>

<header class="masthead bg-primary text-white text-left">
    <div class="container d-flex align-items-left flex-column">

        <h1 class="mb-4">{% trans %} Your legal texts {% endtrans %}</h1>

        <div class="row">
            <div class="col-sm-2">
                <img class="img-fluid w-50 mb-5 mt-2" src="{{ asset('images/rabbit.png') }}" alt="">
            </div>
            <div class="col-sm-10">
                <div class="row mb-2">
                    <div class="col-sm-12">
                        Enlace permanente: <a id="permanent_link" href="{{ url('web_analysis', { hash: hash }) }}" class="font-weight-bold">{{ url('web_analysis', { hash: hash }) }}</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <a tabindex="0" class="btn btn-lg btn-secondary" role="button" onclick="copyToClipboard('permanent_link', 'copyButtonTooltip')" onmouseout="outOfButtonFunc('copyButtonTooltip')">
                            Copiar enlace
                            <span class="tooltiptext hidden" id="copyButtonTooltip"></span>
                        </a>
                        <a tabindex="0" class="btn btn-lg btn-info" role="button" data-toggle="popover" data-trigger="focus" title="Enlace permanente" data-content="Copia este enlace para volver aquí en cualquier momento.">
                            ¿Qué es esto?
                        </a>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a tabindex="0" class="btn btn-lg btn-secondary" role="button">
                            Descargar textos legales
                        </a>
                    </div>
                </div>
                <div class="progress mt-2 mb-2">
                    <div class="progress-bar bg-success" role="progressbar" style="width: {{ analysis.percents.total }}%;" aria-valuenow="{{ analysis.percents.total }}" aria-valuemin="0" aria-valuemax="100">
                        {{ analysis.percents.total }}%
                    </div>
                </div>
            </div>
        </div>
        
        <ul class="nav nav-tabs" id="legalTextsTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="cookies-tab" data-toggle="tab" href="#cookies" role="tab" aria-controls="cookies" aria-selected="true"> {% trans %} Cookies policy {% endtrans %} </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="privacy-tab" data-toggle="tab" href="#privacy" role="tab" aria-controls="privacidad" aria-selected="false"> {% trans %} Privacy policy {% endtrans %} </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="terms-tab" data-toggle="tab" href="#terms" role="tab" aria-controls="terminos" aria-selected="false"> {% trans %} Legal terms {% endtrans %} </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="forms-tab" data-toggle="tab" href="#forms" role="tab" aria-controls="terminos" aria-selected="false"> {% trans %} Forms {% endtrans %} </a>
            </li>
        </ul>
        <div class="tab-content" id="legalTextsTabContent">
            <div class="tab-pane fade show active" id="cookies" role="tabpanel" aria-labelledby="cookies-tab">
                {% include 'texts/cookies.html.twig'  with {'site': analysis.url, 'cookies': analysis.cookies, 'percent': analysis.percents.cookies, 'callback': url('web_analysis', { hash: analysis.hash }) } %}
            </div>
            <div class="tab-pane fade" id="privacy" role="tabpanel" aria-labelledby="privacy-tab">
                {% include 'texts/privacy.html.twig'  with {'site': analysis.url, 'analysis': analysis, 'percent': analysis.percents.privacy, 'callback': url('web_analysis', { hash: analysis.hash }) } %}
            </div>
            <div class="tab-pane fade" id="terms" role="tabpanel" aria-labelledby="terms-tab">
                <h2> {% trans %} Legal terms {% endtrans %} </h2>
            </div>
            <div class="tab-pane fade" id="forms" role="tabpanel" aria-labelledby="forms-tab">
                <h2> {% trans %} Forms {% endtrans %} </h2>
            </div>
        </div>

    </div>
</header>

{% endblock %}

{% block scripts %}
    <script language="javascript">
        $(function() {
            $(function () {
                $('[data-toggle="popover"]').popover()
            })
            $('.popover-dismiss').popover({
                trigger: 'focus'
            })
            var hash = window.location.hash;
            var tabs = ['#cookies', '#privacy', '#terms', '#forms'];

            if (tabs.includes(hash)) {
                $('.nav-link').removeClass('active');
                $('.tab-pane').removeClass('active');
                $('.tab-pane').removeClass('show');
                $(hash).addClass('active');
                $(hash).addClass('show');
                $('.nav-link' + hash + '-tab').addClass('active');
            }
        });
    </script>
    <script language="javascript">
        function copyToClipboard(id, tooltip_id) {
            (function() {
                function selectText(element) {
                    var doc = document
                        , text = element
                        , range, selection
                    ;
                    if (doc.body.createTextRange) { //ms
                        range = doc.body.createTextRange();
                        range.moveToElementText(text);
                        range.select();
                    } else if (window.getSelection) { //all others
                        selection = window.getSelection();
                        range = doc.createRange();
                        range.selectNodeContents(text);
                        selection.removeAllRanges();
                        selection.addRange(range);
                    }
                }
                selectText(document.getElementById(id));
            })();
            document.execCommand("Copy");
            var tooltip = document.getElementById(tooltip_id);
            tooltip.innerHTML = "Copiado al portapapeles!";
            document.getElementById(tooltip_id).classList.remove('hidden');
            (function() {
                function unselectText() {
                    var selection;
                    if (window.getSelection) { //real browsers
                        selection = window.getSelection();
                        selection.removeAllRanges();
                    } else { //ms
                        document.selection.empty();
                    }
                }
                unselectText();
            })();
        }

        function outOfButtonFunc(tooltip_id) {
            document.getElementById(tooltip_id).classList.add('hidden');

        }
    </script>
{% endblock %}

templates/web/company-edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% trans %} Edit company info {% endtrans %} {% endblock %}

{% block body %}

    <header class="masthead bg-primary text-white text-left">
        <div class="container d-flex align-items-left flex-column">

            <h1>{% trans %} Edit company info {% endtrans %}</h1>

            {{ form_start(form) }}
                {{ form_widget(form) }}
                <input class="btn btn-secondary mt-4 mb-4" type="submit" value="{% trans %} Save {% endtrans %}" />
            {{ form_end(form) }}

        </div>
    </header>

{% endblock %}

templates/web/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% trans %} Your web {% endtrans %} {% endblock %}

{% block body %}

    <header class="masthead text-left">
        <div class="container d-flex align-items-left flex-column">
            <h3> {% trans %} Where is your website published? {% endtrans %} </h3>
            <div class="row">

                <div class="col-md-10 col-lg-10">
                    {{ form_start(form) }}
                        {{ form_widget(form) }}
                        <input class="btn btn-primary mt-4 mb-4" type="submit" value="{% trans %} Send {% endtrans %}" />
                    {{ form_end(form) }}
                </div>

            </div>
        </div>
    </header>

{% endblock %}