src/Entity/Cookie.php
<?php

namespace App\Entity;

use App\Service\CookieService\InvalidCookieException;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CookieRepository")
 */
class Cookie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $origin;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $published;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $goal = '';

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type = '';

    /**
     * @ORM\Column(type="integer")
     */
    private $expiration = -1;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $expirationTime;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $path;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $httpOnly;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $thirdParty;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $secure;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $usageUrl;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $optoutUrl;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getOrigin(): ?string
    {
        return $this->origin;
    }

    public function setOrigin(string $origin): self
    {
        $this->origin = $origin;

        return $this;
    }

    public function getPublished(): ?\DateTimeInterface
    {
        return $this->published;
    }

    public function setPublished(\DateTimeInterface $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getGoal(): ?string
    {
        return $this->goal;
    }

    public function setGoal(string $goal): self
    {
        $this->goal = $goal;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getExpiration(): ?int
    {
        return $this->expiration;
    }

    public function setExpiration(int $expiration): self
    {
        $this->expiration = $expiration;

        return $this;
    }

    public function getExpirationTime(): ?string
    {
        return $this->expirationTime;
    }

    public function setExpirationTime(string $expirationTime): self
    {
        $this->expirationTime = $expirationTime;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getHttpOnly(): ?bool
    {
        return $this->httpOnly;
    }

    public function setHttpOnly(bool $httpOnly): self
    {
        $this->httpOnly = $httpOnly;

        return $this;
    }

    public function getThirdParty(): ?bool
    {
        return $this->thirdParty;
    }

    public function setThirdParty(bool $thirdParty): self
    {
        $this->thirdParty = $thirdParty;

        return $this;
    }

    public function getSecure(): ?bool
    {
        return $this->secure;
    }

    public function setSecure(bool $secure): self
    {
        $this->secure = $secure;

        return $this;
    }

    public function getUsageUrl(): ?string
    {
        return $this->usageUrl;
    }

    public function setUsageUrl(?string $usageUrl): self
    {
        $this->usageUrl = $usageUrl;

        return $this;
    }

    public function getOptoutUrl(): ?string
    {
        return $this->optoutUrl;
    }

    public function setOptoutUrl(?string $optoutUrl): self
    {
        $this->optoutUrl = $optoutUrl;

        return $this;
    }

    public function getComplete()
    {
        if (empty($this->name) || empty($this->origin)) {
            throw new InvalidCookieException();
        }
        return (!empty($this->goal) && !empty($this->type));
    }

    public function __toString()
    {
        return '    Cookie {'
             . '        id = '             . $this->getId()
             . '        name = '           . $this->getName()
             . '        origin = '         . $this->getOrigin()
             . '        published = '      . $this->getPublished()
             . '        goal = '           . $this->getGoal()
             . '        type = '           . $this->getType()
             . '        expiration = '     . $this->getExpiration()
             . '        expirationTime = ' . $this->getExpirationTime()
             . '        path = '           . $this->getPath()
             . '        httpOnly = '       . $this->getHttpOnly()
             . '        thirdParty = '     . $this->getThirdParty()
             . '        secure = '         . $this->getSecure()
             . '        usageUrl = '       . $this->getUsageUrl()
             . '        optoutUrl = '      . $this->getOptoutUrl()
             . '    }';
    }
}

templates/texts/cookies.html.twig
<div class="row">
    <div class="col-sm-6">
        <h1>Política de Cookies</h1>
    </div>
    <div class="col-sm-6">
        <div class="progress mb-2">
            <div class="progress-bar bg-success" role="progressbar" style="width: {{ percent }}%;" aria-valuenow="{{ percent }}" aria-valuemin="0" aria-valuemax="100">
                {{ percent }}%
            </div>
        </div>
    </div>
</div>

<p>
    Actualizada a {{ "now"|date("d/m/Y") }}
</p>

<h2>Información esencial</h2>

<ul>
    <li>Datos del titular y contacto</li>
</ul>


<h2>Configurar y deshabilitar las cookies</h2>

<p>
    Puedes permitir, bloquear o eliminar las cookies instaladas
    en tu dispositivo desde tu navegador web.
    A continuación puedes encontrar cómo configurar las cookies
    en cada navegador:
</p>

<ul>
    <li><a href="http://windows.microsoft.com/es-es/windows-10/edge-privacy-faq" target="_blank">Edge</a></li>
    <li><a href="https://support.google.com/chrome/answer/95647?hl=es" target="_blank">Google Chrome</a></li>
    <li><a href="http://windows.microsoft.com/es-es/internet-explorer/delete-manage-cookies#ie=ie-11" target="_blank">Internet Explorer 11</a></li>
    <li><a href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we" target="_blank">Mozilla Firefox</a></li>
    <li><a href="http://help.opera.com/Linux/10.60/es-ES/cookies.html" target="_blank">Opera</a></li>
    <li><a href="https://support.apple.com/kb/PH19214?viewlocale=es_ES&locale=es_ES" target="_blank">Safari</a></li>
    <li><a href="https://support.apple.com/es-es/HT201265" target="_blank">Safari Mobile</a></li>
</ul>

<h3>1.- Tipos y usos</h3>

<p>
    Una cookie es un fichero de texto que se envía al navegador web de tu ordenador, móvil o tablet
    y que sirve para almacenar y recuperar información sobre la navegación realizada.
    Por ejemplo, recordar tu nombre de usuario y contraseña o las preferencias de tu perfil.
</p>

<h3>2.- ¿Qué tipos de cookies hay?</h3>

<p>
    Según quién las gestiona:
</p>

<ul>
    <li><strong>Cookies propias</strong>; se envían a tu navegador desde nuestros equipos o dominios web.</li>
    <li><strong>Cookies de terceros</strong>; se envían a tu navegador desde un equipo o dominio web que no gestionamos nosotros directamente, sino una tercera entidad como por ejemplo Google.</li>
</ul>

<p>
    En función del tiempo que están activas, hay:
</p>

<ul>
    <li><strong>Cookies de sesión</strong>; permanecen en el archivo de cookies de tu navegador hasta que abandonas la página web, de modo que ninguna queda en tu dispositivo.
    <li><strong>Cookies persistentes</strong>; permanecen en tu dispositivo y nuestra web las lee cada vez que realizas una nueva visita. Estas cookies dejan de funcionar pasada una fecha concreta.
</ul>

<p>
    Finalmente, y según su finalidad, tenemos:
</p>

<ul>
    <li><strong>Cookies técnicas</strong>; mejoran la navegación y el buen funcionamiento de la web.
    <li><strong>Cookies de personalización</strong>; permiten acceder al servicio con unas características predefinidas en función de una serie de criterios.
    <li><strong>Cookies de análisis</strong>; permiten medir y analizar estadísticamente el uso que se hace del servicio prestado.
</ul>

<p>
    Cookies usadas por <a href="{{site}}" target="_blank">{{site}}</a>:
</p>

<table class="table table-dark table-bordered table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th>Nombre</th>
            <th>Origen</th>
            <th>Finalidad</th>
            <th>Tipo</th>
            <th>Caducidad</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for cookie in cookies %}
        <tr>
            <td>{{ cookie.name }}</td>
            <td>{{ cookie.origin }}</td>
            <td>{{ cookie.goal }}</td>
            <td>{{ cookie.type }}</td>
            <td>{{ cookie.expirationTime }}</td>
            {% if cookie.complete == false %}
                <td>
                    <a href="{{ url('cookie_edit', { id: cookie.id, callback: callback }) }}" class="btn btn-lg btn-warning" role="button">
                        Completar
                    </a>
                </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/texts/cookies.md.twig
# Política de Cookies

Actualizada a {{ "now"|date("d/m/Y") }}

## Información esencial
 - Datos del titular y medios de contacto

## Cómo configurar y deshabilitar las cookies

Puedes permitir, bloquear o eliminar las cookies instaladas en tu dispositivo desde tu navegador web.
Si no permites la instalación de cookies en tu dispositivo, puede que la experiencia de navegación empeore.
A continuación puedes encontrar cómo configurar las cookies en cada navegador:

 - [Edge](http://windows.microsoft.com/es-es/windows-10/edge-privacy-faq)
 - [Google Chrome](https://support.google.com/chrome/answer/95647?hl=es)
 - [Internet Explorer 11](http://windows.microsoft.com/es-es/internet-explorer/delete-manage-cookies#ie=ie-11)
 - [Mozilla Firefox](https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we)
 - [Opera](http://help.opera.com/Linux/10.60/es-ES/cookies.html)
 - [Safari](https://support.apple.com/kb/PH19214?viewlocale=es_ES&locale=es_ES)
 - [Safari Mobile](https://support.apple.com/es-es/HT201265)

### 1.- Tipos y usos

Una cookie es un fichero de texto que se envía al navegador web de tu ordenador, móvil o tablet
y que sirve para almacenar y recuperar información sobre la navegación realizada.
Por ejemplo, recordar tu nombre de usuario y contraseña o las preferencias de tu perfil.

### 2.- ¿Qué tipos de cookies hay?

Según quién las gestiona:

 - **Cookies propias**; se envían a tu navegador desde nuestros equipos o dominios web.

 - **Cookies de terceros**; se envían a tu navegador desde un equipo o dominio web que no gestionamos nosotros directamente, sino una tercera entidad como por ejemplo Google.

En función del tiempo que están activas, hay:

 - **Cookies de sesión**; permanecen en el archivo de cookies de tu navegador hasta que abandonas la página web, de modo que ninguna queda en tu dispositivo.

 - **Cookies persistentes**; permanecen en tu dispositivo y nuestra web las lee cada vez que realizas una nueva visita. Estas cookies dejan de funcionar pasada una fecha concreta.

Finalmente, y según su finalidad, tenemos:

 - **Cookies técnicas**; mejoran la navegación y el buen funcionamiento de la web.

 - **Cookies de personalización**; permiten acceder al servicio con unas características predefinidas en función de una serie de criterios.

 - **Cookies de análisis**; permiten medir y analizar estadísticamente el uso que se hace del servicio prestado.

Cookies usadas por [{{site}}]({{site}}):

| Nombre    | Origen   | Finalidad | Tipo     | Caducidad  |
|-----------|----------|-----------|----------|------------|
{% for cookie in cookies %}
| {{ cookie.name }} | {{ cookie.origin }} | {{ cookie.goal }} | {{ cookie.type }} | {{ cookie.expirationTime }} |
{% endfor %}

templates/texts/field.html.twig
{% if value is empty %}
    <span class="string-to-complete"></span>
    <a href="{{ url }}" class="btn btn-lg btn-warning" role="button">
        Completar
    </a>
{% else %}
    {{ value }}
{% endif %}